name: DespawnedItems
version: 1.0
main: com.popupmc.despawneditems.DespawnedItems
description: Despawned Items
author: junebug12851
api-version: 1.15

commands:
  despi:
    description: Accesses despawned items command
    usage: /despi
    permission: despi.use
    permission-message: You do not have permission to use despawned items
  recycle:
    description: Recycles the item in your hand
    usage: /recycle
    permission: recycle.use
    permission-message: You do not have permission to use despawned items

permissions:
  despi.use:
    description: Allows you to use despi
  despi.elevate:
    description: Allows you to manage despi
